### ISSUE TITLE
Notes from 7-24-2017

### ISSUE THREAD

**Issue by dmleong** [TheLucasMoore/consensual_software#2]
## Random stuff 
- [x] Medium editorial 
- [x] Twitter account (that publishes Medium stuff) (@dmleong)
  - Share highlighted quotes from personal Medium accounts
  - [x] @dmleong to create email account for consensualsoftware.com and share with @TheLucasMoore 
  - [x] @dmleong to reset Twitter password and use consensual software email 
- [ ] Collect emails when they take oath to build network (@thelucasmoore)
- [x] @dmleong to fix her local dev env and Ruby versions 😬 
- [ ] @dmleong to follow up with Manuel Pais about Consensual IoT 
- [x] Make a Slack (@dmleong)
- [x] @TheLucasMoore transfer domain to @dmleong
- [ ] Fix Medium header image to something that isn't a dog  (@thelucasmoore)
 - https://medium.com/consensual-software
 - https://thenounproject.com/ 
 - http://logodust.com/ (same logo as Consensual Advertising)

### Website 
- [x] Finalize theme 
- [x] Add `About` page 
  - [x] What is consent?  https://github.com/TheLucasMoore/consensual_software/issues/3
  - [x] About the people doing this  https://github.com/TheLucasMoore/consensual_software/issues/4
  - [x] Hip circular avatars with css filters ⚪️  (@dmleong) 
- [ ] Resources https://github.com/TheLucasMoore/consensual_software/issues/5
- [ ] Open a PR and sign the oath  (@thelucasmoore) 
  - [ ] @TheLucasMoore to make a PR template for oath
- [ ] Consensual software definition (@dmleong) https://github.com/TheLucasMoore/consensual_software/issues/6

## Intended audience? 
- Software developers 
- Product/Project managers 
- Marketing/Advertising people 
- Privacy-minded people 

## Scheduling 
- Once a month checkin 
- Once a month blog post 
- Ad hoc tweeting/Medium shares 
- Real time Slack 

## Posts to write 
- [ ] What is consent? 
- [ ] Book reviews _Hooked_ @TheLucasMoore 
- [ ] Privacy/Consent by design @dmleong https://www.ipc.on.ca/wp-content/uploads/2013/09/pbd-primer.pdf
- [ ] Metrics that don't include consent - what do they mean? (NOTHING) 
- [ ] Consensual IoT (Manuel)

**Comment by dmleong** [comment]
Stale stuff, closing out
